"""Phase 2H - a narrow LLM abstraction.

`LLMClient` is the only surface the orchestrator (orchestrator.py) talks
to - no LangGraph node imports `openai`/`langchain_openai` directly, so
swapping providers never touches graph logic. Exactly one real
implementation (`OpenAIChatClient`) and one deterministic test double
(`FakeLLMClient`) exist this phase - never multiple agent frameworks,
never a hardcoded provider baked into the graph itself.

The LLM's output is always validated against `LLMDecision`, a strict
Pydantic model with an enum-constrained `action` and
`requested_evidence_type` - this is the core mitigation against prompt
injection (Phase 2H §28): whatever text the LLM was shown (including
any graph-derived data), the only thing it can ever produce that the
orchestrator acts on is one of four fixed action values plus one of four
fixed evidence-type values. It cannot invoke arbitrary code, bypass
`PolicyEngine`, or mutate a `CaseRecord` directly - see
orchestrator.py's module docstring for the full boundary.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from enum import Enum

from pydantic import BaseModel, ConfigDict, ValidationError

from app.agent.state import RequestedEvidenceType
from app.config import Settings, get_settings


class LLMNotConfiguredError(RuntimeError):
    """Raised by `OpenAIChatClient.__init__` when no real LLM credential
    is configured - the real client fails loudly rather than silently
    falling back to a fake or a different provider (Phase 2H §17)."""


class LLMDecisionAction(str, Enum):
    INVESTIGATE = "investigate"
    REQUEST_MORE_EVIDENCE = "request_more_evidence"
    CONTINUE = "continue"  # evidence is sufficient - proceed to policy evaluation
    FINISH = "finish"  # same effect as CONTINUE this phase - proceed to policy evaluation


class LLMDecision(BaseModel):
    """The ONLY thing the orchestrator reads from the LLM's control-flow
    turn. `reason` is free text (used only in observability messages,
    never fed back into a deterministic calculation)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    action: LLMDecisionAction
    requested_evidence_type: RequestedEvidenceType | None = None
    reason: str = ""


class MalformedLLMOutputError(ValueError):
    """Raised when an LLM client's raw output cannot be validated as a
    LLMDecision - caught by the orchestrator's decide_next_step node and
    turned into AgentStatus.FAILED, never a fabricated decision."""


def parse_llm_decision(raw: object) -> LLMDecision:
    """The single validation choke point every LLMClient implementation's
    output passes through before the orchestrator trusts it."""
    try:
        return LLMDecision.model_validate(raw)
    except ValidationError as exc:
        raise MalformedLLMOutputError(str(exc)) from exc


class LLMClient(ABC):
    @abstractmethod
    def decide_next_step(self, state_summary: dict) -> LLMDecision: ...

    @abstractmethod
    def generate_explanation(self, state_summary: dict) -> str: ...


class FakeLLMClient(LLMClient):
    """Deterministic test double - the ONLY LLM the main offline/
    integration test suite depends on (Phase 2H §16). Scripted with a
    fixed sequence of decisions; once exhausted, defaults to CONTINUE
    (never loops forever on its own)."""

    def __init__(
        self,
        decisions: list[LLMDecision] | list[dict] | None = None,
        *,
        explanation: str = "SYNTHETIC TEST EXPLANATION - generated by FakeLLMClient, not a real model.",
    ) -> None:
        self._decisions = [d if isinstance(d, LLMDecision) else LLMDecision.model_validate(d) for d in (decisions or [])]
        self._index = 0
        self._explanation = explanation
        self.calls = 0

    def decide_next_step(self, state_summary: dict) -> LLMDecision:
        self.calls += 1
        if self._index < len(self._decisions):
            decision = self._decisions[self._index]
            self._index += 1
            return decision
        return LLMDecision(action=LLMDecisionAction.CONTINUE, reason="fake default: no more scripted decisions")

    def generate_explanation(self, state_summary: dict) -> str:
        return self._explanation


class MalformedLLMClient(LLMClient):
    """Test double for Phase 2H §23 Scenario 5 - returns a raw value
    that fails `LLMDecision` validation, to exercise the orchestrator's
    malformed-output handling without needing a real, flaky LLM."""

    def __init__(self, raw_output: object | None = None) -> None:
        self._raw_output = raw_output if raw_output is not None else {"action": "not_a_real_action"}

    def decide_next_step(self, state_summary: dict) -> LLMDecision:
        return parse_llm_decision(self._raw_output)  # deliberately raises MalformedLLMOutputError

    def generate_explanation(self, state_summary: dict) -> str:
        return "unreachable"


class OpenAIChatClient(LLMClient):
    """The one real provider integration this phase ships. Requires
    explicit configuration (`Settings.llm_configured`) - constructed
    lazily and only when actually needed, so the deterministic backend
    and its test suite never require an API key to run."""

    def __init__(self, settings: Settings | None = None) -> None:
        settings = settings or get_settings()
        if not settings.llm_configured:
            raise LLMNotConfiguredError(
                "OPENAI_API_KEY / OPENAI_MODEL are not set. OpenAIChatClient requires "
                "explicit LLM configuration - it will not silently substitute a fake "
                "client or a different provider."
            )
        from langchain_openai import ChatOpenAI

        self._settings = settings
        base_kwargs = {
            "model": settings.openai_model,
            "api_key": settings.openai_api_key.get_secret_value(),
            "timeout": settings.llm_timeout_seconds,
            "max_retries": settings.llm_max_retries,
        }
        if settings.openai_base_url:
            base_kwargs["base_url"] = settings.openai_base_url
        self._model = ChatOpenAI(**base_kwargs)
        self._decision_model = self._model.with_structured_output(LLMDecision)

    def decide_next_step(self, state_summary: dict) -> LLMDecision:
        from app.agent.prompts import build_decision_messages

        messages = build_decision_messages(state_summary)
        result = self._decision_model.invoke(messages)
        return parse_llm_decision(result)

    def generate_explanation(self, state_summary: dict) -> str:
        from app.agent.prompts import build_explanation_messages

        messages = build_explanation_messages(state_summary)
        response = self._model.invoke(messages)
        return str(response.content)
